language: python
cache: pip
python:
#  - "3.6"
#  - "3.7"
  - "3.8"
before_install:
  - sudo apt-add-repository ppa:qameta/allure
  - sudo apt-get update
  - sudo apt-get install allure
install:
  - pip install -r requirements.txt
script:
  - bash ./run-ci.sh
after_success:
  - codecov