language: python
python:
#  - "3.6"
#  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - flake8 --config=flake8-config.ini
  - pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
